server:
  shutdown: graceful
  port: 8180
  
spring:
  datasource:
    url: jdbc:h2:mem:demodb
    username: sa
    password: 
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
      auto-commit: true
      pool-name: master      
  lifecycle:
    timeout-per-shutdown-phase: 30s
    
management:
  server:
    port: 8192
  endpoints:  
    web:
      exposure:
        include: 
        - 'health'
        - 'info'
        - 'prometheus'
        - 'metrics'
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true